INPUT_FILE = "data_input/order_details.csv"
REF_FILE = "data_input/restaurant_details.csv"
OUTPUT_CLEAN = "data_output/orders_cleaned.csv"
OUTPUT_REJECT = "data_output/orders_rejected.csv"
OUTPUT_AGG = "data_output/aggregated_data.csv"
DB_CONNECTION = "sqlite:///etl.db"
TABLE_NAME = "processed_data"