INPUT_FILE = "data_input/order_details.csv"
REF_FILE = "data_input/restaurant_details.csv"
BASE_OUTPUT = "data_output"
USER = "username"
PASS = "password"
URL = "sqlite:///etl.db"
TABLE_NAME = "processed_data"